---
ENABLED: true # If not true, HungerPE will disable
HG-WORLDS: # These are the worlds that players play on
    - world
    - world2
LOBBY-WORLD: lobby # This is the world that players wait in to play
SPAWN-WORLD: spawn # This is the world that players go on first join (Main Spawn)
JOIN-MESSAGE: "Welcome To HungerPE! Use /hg join To Play!" # Message sent to players when they join
...

